spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "Csee88923839"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: demo
